DROP TABLE Owner CASCADE CONSTRAINTS;
DROP TABLE Car CASCADE CONSTRAINTS;

CREATE TABLE Owner
(	svnr VARCHAR(10) PRIMARY KEY,
	name VARCHAR2(30)
);

CREATE TABLE Car
(	fgnr INTEGER PRIMARY KEY,
	name VARCHAR2(30),
	type VARCHAR(30),
  svnr_Owner VARCHAR(10) NOT NULL,
	CONSTRAINT fkCar FOREIGN KEY (svnr_Owner) REFERENCES Owner(svnr)
);

INSERT INTO Owner VALUES(0001,'Owner1');
INSERT INTO Owner VALUES(0002,'CeDe AG');
INSERT INTO Owner VALUES(0003,'ÖFBB');

INSERT INTO Car VALUES(1,'Model S','Tesla',0001);
INSERT INTO Car VALUES(2,'Chiron','Buggatti',0001);
INSERT INTO Car VALUES(3,'TT','Audi',0002);

Select * from Owner;
Select * from Car;